INSERT INTO public.fw_seg_roles (code) VALUES
	 ('ROLE_ADMIN'),
	 ('ROLE_USER_AVZDO'),
	 ('ROLE_USER_BASICO'),
	 ('ROLE_BACK_ADMIN_OPERARIOS'),
	 ('ROLE_BACK_ADMIN_GRUPOS'),
	 ('ROLE_BACK_ADMIN_MAESTRAS'),
	 ('ROLE_FRONT_CITAS_PROPIAS'),
	 ('ROLE_FRONT_EMPRESAS'),
	 ('ROLE_FRONT_USUARIOS'),
	 ('ROLE_FRONT_CALENDARIOS');
INSERT INTO public.fw_seg_roles (code) VALUES
	 ('ROLE_FRONT_CITAS_GLOBAL'),
	 ('ROLE_FRONT_INFORMES');