INSERT INTO public.ma_accions_sfe (codigo,nome) VALUES
	 ('999','F.S.E. Parquetista'),
	 ('999','F.S.E. Técnico de merchadising'),
	 ('999','F.S.E. Monitor de educación ambiental'),
	 ('999','URBAN Manipulación peixe'),
	 ('999','URBAN Maquetismo naval'),
	 ('999','URBAN Mecánico parque'),
	 ('999','URBAN Monitor deportes naúticos'),
	 ('999','URBAN Redeiro'),
	 ('999','URBAN Cociñeiro marítimo'),
	 ('1','ORIENTACIÓN');
INSERT INTO public.ma_accions_sfe (codigo,nome) VALUES
	 ('999','E.O. Pat. Hist. Albanelería'),
	 ('999','E.O. Pat. Hist. Xardinería'),
	 ('999','E.O. Pat. Hist. Carpintería'),
	 ('999','E.O. Lagares - Mantemento de xardíns'),
	 ('999','E.O. Lagares - Restauración áreas degradadas'),
	 ('999','E.O. Lagares - Viveirismo'),
	 ('999','E.O. Lagares - Orientación medioambiental'),
	 ('999','E.O. Forestal - Motoserrista'),
	 ('999','E.O. Forestal - Maniquinista forestal'),
	 ('999','E.O. Forestal - Auxiliar forestal');
INSERT INTO public.ma_accions_sfe (codigo,nome) VALUES
	 ('999','E.O. Forestal -Axudante de campo'),
	 ('999','F.S.E. Traballador forestal'),
	 ('999','F.S.E. Emprendedor turístico'),
	 ('999','F.S.E. Analista de R.S.U.'),
	 ('999','E.O. Pat. Hist. Cantería'),
	 ('999','F.S.E. Delineante cartográfico'),
	 ('999','F.S.E. Carniceiro'),
	 ('999','F.S.E. Técnico en control de calidade'),
	 ('999','F.S.E. Administrativo en xestión fiscal da empresa'),
	 ('999','F.S.E. Enfermería de xestión (supervisores/as)');
INSERT INTO public.ma_accions_sfe (codigo,nome) VALUES
	 ('999','F.S.E. Escaparatista'),
	 ('999','F.S.E. Inglés técnico'),
	 ('999','SÍSIFO'),
	 ('999','URBAN Mód. rehab. urb. - Albanelería'),
	 ('999','URBAN Mód. rehab. urb. - Cantería'),
	 ('999','URBAN Mód. rehab. urb. - Carpintería'),
	 ('999','URBAN Mód. rehab. urb. - Forxa'),
	 ('999','URBAN Mód. rehab. urb. - Pintura'),
	 ('999','URBAN Auxiliar de camareiro'),
	 ('999','URBAN Animador turístico do casco vello');
INSERT INTO public.ma_accions_sfe (codigo,nome) VALUES
	 ('999','E.O. X.H. Castrelos - Albanelería'),
	 ('999','E.O. X.H. Castrelos - Xardinería'),
	 ('999','E.O. X.H. Castrelos - Carpintería'),
	 ('999','E.O. X.H. Castrelos - Cantería'),
	 ('999','URBAN Manipulación de peixe fresco'),
	 ('999','URBAN Redeiro básico'),
	 ('999','URBAN Redeiro avanzado'),
	 ('999','URBAN Máquinas e cintas de parque de pesca'),
	 ('999','URBAN Contram.  instal. náutico-deportivas'),
	 ('999','URBAN Frío naval');
INSERT INTO public.ma_accions_sfe (codigo,nome) VALUES
	 ('999','URBAN Fibra de vidrio'),
	 ('999','URBAN Acuaroloxía profesional'),
	 ('999','URBAN Manipul. e transform. peixe conxelado'),
	 ('999','PROMIL'),
	 ('999','E.O. Mar de Vigo - Actividades Náutico Turísticas'),
	 ('999','E.O. Mar de Vigo - Novas Técnicas de Construcción Naval'),
	 ('999','E.O. Mar de Vigo - Carpintería de Ribeira'),
	 ('999','E.O. Mar de Vigo - Instalacións Marítmo Deportivas'),
	 ('999','ASISTE'),
	 ('999','O.E. Vigozoo - Carpintería');
INSERT INTO public.ma_accions_sfe (codigo,nome) VALUES
	 ('999','O.E. Vigozoo - Construcción'),
	 ('999','O.E. Vigozoo - Xardinería'),
	 ('999','ABEIRO'),
	 ('2','BOLSA DE EMPREGO'),
	 ('999','E.O. Mar de Vigo II - Novas Técnicas de Construcción Naval'),
	 ('999','E.O. Mar de Vigo II - Carpintería de Ribeira'),
	 ('999','E.O. Mar de Vigo II - Actividades Náutico Turísticas'),
	 ('999','Alicerce Animación - 3ª idade e discapacidades'),
	 ('999','Alicerce Adiccións'),
	 ('999','Alicerce Mediación');
INSERT INTO public.ma_accions_sfe (codigo,nome) VALUES
	 ('999','O.E. Vigozoo II - Construcción'),
	 ('999','O.E. Vigozoo II - Carpintería'),
	 ('999','O.E. Vigozoo II - Xardinería'),
	 ('999','Alicerce Animación/MTL - Tempo libre'),
	 ('3','BIAL 1'),
	 ('4','BIAL 2'),
	 ('6','E.O. Mar de Vigo III -  Actividades Náutico Turísticas'),
	 ('7','E.O. Mar de Vigo III - Carpintería de Ribeira'),
	 ('8','E.O. Mar de Vigo III - Novas Técnicas de Construcción Naval'),
	 ('999','Actívate - Limpeza');
INSERT INTO public.ma_accions_sfe (codigo,nome) VALUES
	 ('999','Actívate - Teleoperación'),
	 ('999','Actívate - Axudante de cociña'),
	 ('999','Actívate - Lavandería'),
	 ('999','Actívate - Condución'),
	 ('999','Actívate - Servizos domiciliarios'),
	 ('999','O.E. Vigozoo III - Carpintaría'),
	 ('999','O.E. Vigozoo III - Construción'),
	 ('999','O.E. Vigozoo III - Fontanaría e electricidade'),
	 ('999','O.E. Vigozoo III - Educación ambiental'),
	 ('5','BIAL 3');
INSERT INTO public.ma_accions_sfe (codigo,nome) VALUES
	 ('999','UTIL 1'),
	 ('999','E.O. Mar de Vigo IV - Actividades Náuticas'),
	 ('999','E.O. Mar de Vigo IV - Construcción Naval en Laminados de Madeira'),
	 ('999','E.O. Mar de Vigo IV - Carpintería de Ribeira'),
	 ('999','Vigo Emprega'),
	 ('999','E.O. Vigozoo Construción'),
	 ('999','E.O. Vigozoo Xardinería'),
	 ('999','E.O. Vigozoo Carpintería Metálica'),
	 ('999','IMOS TRABALLAR'),
	 ('999','E.O. Vigoornamental - Albanelería');
INSERT INTO public.ma_accions_sfe (codigo,nome) VALUES
	 ('999','E.O. Vigoornamental - Carpintaría'),
	 ('999','E.O. Vigoornamental - Fontanaría'),
	 ('999','E.O. Vigo Zoo Carpintería Metálica'),
	 ('999','E.O. Vigo Zoo Albanelería'),
	 ('999','E.O. Vigo Zoo Xardinería'),
	 ('999','E.O. Mar de Vigo V Carpintería de ribeira'),
	 ('999','E.O. Mar de Vigo V Actividades Nauticas'),
	 ('999','E.O. Mar de Vigo V Tecnicas de construción'),
	 ('999','UTIL 2'),
	 ('999','UTIL 3');
INSERT INTO public.ma_accions_sfe (codigo,nome) VALUES
	 ('999','UTIL'),
	 ('999','Vigo Emprega 2012-13'),
	 ('999','O.E. Vigo Atende'),
	 ('VE13-14','Vigo Emprega 2013-2014'),
	 ('VINT2013','Vigo Integra'),
	 ('OEVigoCapacita1','O.E. Vigo Capacita I'),
	 ('OEVigoCapacita2','O.E. Vigo Capacita II'),
	 ('O.E. Vigo Capacita III','Obradoiro de Emprego Vigo Capacita III'),
	 ('20171','O.E. FORMAWEB'),
	 ('20172','O.E. Vigo Capacita III');
INSERT INTO public.ma_accions_sfe (codigo,nome) VALUES
	 ('20173','O.E. Vigo Capacita IV'),
	 ('VINT2021','Vigo Capacita VI'),
	 ('Risga','RISGA 2021');