INSERT INTO public.ma_carnets_conducir (codigo,nome) VALUES
	 (' ','LC-LICENZA CICLOMOTOR'),
	 (' ','LM-LICENZA COCHES MINUSVÁLIDOS'),
	 (' ','LA-LICENZA VEHÍCULO AGRÍCOLA'),
	 (' ','A1-MOTOCICLETAS LIXEIRAS CILIND. MÁXIMA 125 C.C. E POTENCIA MÁXIMA 11 KW'),
	 (' ','A-MOTOCICLETAS, CON/SEN SIDECAR. TRICICLOS/CUADRICICLOS DE MOTOR'),
	 (' ','B-AUTOMÓBIL <=3.500 kg, ASENTOS <=9, CON REMOLQUE <=750 kg'),
	 (' ','BTP-B CON AUTORIZACIÓN PARA VEHÍCULOS PRIORITARIOS'),
	 (' ','C1-AUTOMÓBIL MASA MÁXIMA AUTORIZADA > 3.500 kg E <= 7.500 kg , ASENTOS <= 9'),
	 (' ','C-AUTOMÓBIL MASA MÁXIMA AUTORIZADA > 3.500 kg, ASENTOS <=9'),
	 (' ','D1-AUTOMÓBIL TRANSPORTE PERSOAS, ASENTOS <=17, REMOLQUE <= 750 kg');
INSERT INTO public.ma_carnets_conducir (codigo,nome) VALUES
	 (' ','D-AUTOMÓBIL TRANSPORTE PERSOAS, ASENTOS > 9, REMOLQUE <= 750 kg'),
	 (' ','E-AUTOMÓBIL CLASE B, CON REMOLQUE > 750 kg'),
	 (' ','E-AUTOMÓBIL CLASE B CON AUTORIZACIÓN V.P. (BTP), C'),
	 (' ','E-AUTOMÓBIL CLASE C1, CON REMOLQUE <= 12.000 kg'),
	 (' ','E-AUTOMÓBIL CLASE C, CON REMOLQUE > 750 kg'),
	 (' ','E-AUTOMÓBIL D1, CON REMOLQUE <= 12.000 kg'),
	 (' ','E-AUTOMÓBIL CLASE D, CON REMOLQUE > 750 kg'),
	 (' ','X-DESCOÑECIDO TIPO E'),
	 ('','CAP - Certifificado de Aptitude Profesional');